name: 'CovidNotifierLiteDeploy'
on:
  push:
    branches: [production]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          email: ${{ gustavoduartefaria@gmail.com }} 
          api_key: ${{ f640f352-d621-4f7f-81ca-20fc2464b010 }} # your  heroku api key
          docker_compose_file: './docker-compose.yml'
          heroku_apps: '[{"imagename":"covidnotifierlite","appname":"covidnotifierlite","apptype":"web"}]'
